FROM nginx
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY dist /usr/share/nginx/html

# Bundle nginx conf
COPY default.conf /etc/nginx/conf.d/