version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 8080:80
      - 443:443
    networks:
      app_network:
        ipv4_address: 172.25.1.1
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  backend:
    container_name: backend
    build: ./backend
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      app_network:
        ipv4_address: 172.25.1.2
    command: node server.bundle.js
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'

networks:
  app_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
