version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 8080:80
    networks:
      app_network:
        ipv4_address: 172.25.1.1
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3000:3000
    networks:
      app_network:
        ipv4_address: 172.25.1.2
    command: node server.bundle.js

networks:
  app_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
