version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 8080:80
    networks:
      - app-network
  backend:
    build: ./backend
    ports:
      - 3000:3000
    working_dir: /usr/src/server
    command: node server.bundle.js
    networks:
      - app-network
    depends_on:
      - frontend
networks:
  app-network:
    driver: bridge
